#!/bin/bash
VOSK_MODEL_PATH=[path to your vosk model]

# take mic input
ffmpeg -y -f alsa -i default -acodec pcm_s16le -ac 1 -ar 44100 -t 4 -f wav ~/.cache/audio.wav

# convert it into text & store it in `audio_input`
vosk-transcriber -m $VOSK_MODEL_PATH -i ~/.cache/audio.wav -o ~/.cache/audio_text.txt
read audio_input < ~/.cache/audio_text.txt
